[package]
name = "network-clipboard"
version = "0.1.0"
edition = "2018"

[[bin]]
name = "rcc"
path = "src/rcc.rs"

[[bin]]
name = "rcd"
path = "src/rcd.rs"

[[bin]]
name = "rcp"
path = "src/rcp.rs"

[dependencies]
clap = "4.2.5"
# getopts = "0.2"